apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Values.deployment.backend.name }}
spec:
  selector:
    app: {{ .Values.deployment.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.backend.service.port }}
      targetPort: {{ .Values.deployment.backend.service.port }}
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Values.deployment.frontend.name }}
spec:
  selector:
    app: {{ .Values.deployment.frontend.name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.deployment.frontend.service.port }}
      targetPort: {{ .Values.deployment.frontend.service.port }}
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.statefulset.name }}
spec:
  selector:
    app: {{ .Values.statefulset.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.statefulset.service.port }}
      targetPort: {{ .Values.statefulset.service.port }}
